include: package:flutter_lints/flutter.yaml
plugins:
  riverpod_lint: 3.1.3

analyzer:
  errors:
    unreachable_switch_default: ignore
    unused_element_parameter: ignore
  exclude:
    - '**.g.dart'

linter:
  rules:
    prefer_single_quotes: true
    unnecessary_lambdas: true
    avoid_renaming_method_parameters: false
    prefer_const_constructors: true

formatter:
  trailing_commas: preserve
  page_width: 200
