name: open-authenticator
version: 1.3.1
summary: A cross-platform OTP app, free and open-source.
description: Secure your online accounts with a free, open-source and lovely-crafted app.

base: core24
confinement: strict
grade: stable

slots:
  dbus-open-authenticator:
    interface: dbus
    bus: session
    name: app.openauthenticator

apps:
  open-authenticator:
    command: openauthenticator
    extensions: [gnome]
    plugs:
      - network
    slots:
      - dbus-open-authenticator
parts:
  open-authenticator:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
