name: open-authenticator
version: 1.3.1
summary: A cross-platform OTP app, free and open-source.
description: Secure your online accounts with a free, open-source and lovely-crafted app.

base: core24
confinement: classic
grade: stable

slots:
  dbus-open-authenticator:
    interface: dbus
    bus: session
    name: app.openauthenticator

apps:
  open-authenticator:
    command: open_authenticator
    plugs:
      - network
    slots:
      - dbus-open-authenticator

parts:
  open-authenticator:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libgdk-pixbuf-2.0-dev
      - libatk1.0-dev
      - pkg-config
      - libpam0g-dev
      - libsecret-1-dev
    override-build: |
      snapcraftctl build
    override-prime: |
      snapcraftctl prime
