name: open-authenticator
title: Open Authenticator
version: 1.4.1
summary: A cross-platform OTP app, free and open-source.
description: Secure your online accounts with a free, open-source and lovely-crafted app.
license: GPL-3.0-only
icon: snap/gui/icon.svg
source-code:
  - https://github.com/Skyost/OpenAuthenticator
contact:
  - https://openauthenticator.app/contact/
issues:
  - https://github.com/Skyost/OpenAuthenticator/issues/

base: core24
confinement: strict
grade: stable

slots:
  open-authenticator-dbus:
    interface: dbus
    bus: session
    name: app.openauthenticator

apps:
  open-authenticator:
    command: open_authenticator
    extensions:
      - gnome
    plugs:
      - network
      - polkit
    slots:
      - open-authenticator-dbus
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS

parts:
  open-authenticator:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libpolkit-gobject-1-dev
  polkit-locale:
    plugin: nil
    source: snap/meta/polkit/po
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale
      for po in *.po; do
        lang=${po%.po}
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale/$lang/LC_MESSAGES
        msgfmt $po -o $SNAPCRAFT_PART_INSTALL/usr/share/locale/$lang/LC_MESSAGES/app.openauthenticator.mo
      done
    build-packages:
      - gettext
  polkit-policy:
    plugin: dump
    source: snap/meta/polkit/polkit.app.openauthenticator.policy
    source-type: file
    organize:
      polkit.app.openauthenticator.policy: meta/polkit/polkit.app.openauthenticator.policy

plugs:
  polkit:
    action-prefix: app.openauthenticator

